[general]
name = "Snail"

[versions.4-0-0]
[versions.4-0-0.attrs]
name = { dtype = "str", default = "UNKNOWN" }
# Extents
max_height = { dtype = "f64", default = "1.0" }
max_velocity = { dtype = "f64", default = "60.0" }
sphere_radius = { dtype = "f64", default = "2.0" }

[versions.4-0-0.datasets]
surface_density = { dtype = "f32", shape = "(num_velocity_bins, num_height_bins, num_frames, num_locations)" }
azimuthal_velocity = { dtype = "f32", shape = "(num_velocity_bins, num_height_bins, num_frames, num_locations)" }
radial_velocity = { dtype = "f32", shape = "(num_velocity_bins, num_height_bins, num_frames, num_locations)" }

[versions.4-0-0.fields]
num_frames = { type = "int", value = "num_frames" }
num_velocity_bins = { type = "int", value = "num_velocity_bins" }
num_height_bins = { type = "int", value = "num_height_bins" }
num_locations = { type = "int", value = "num_locations" }

[versions.5-0-0]
[versions.5-0-0.attrs]

[versions.5-0-0.datasets]
surface_density = { dtype = "f64", shape = "(num_velocity_bins, num_height_bins, num_frames, num_locations)" }
azimuthal_velocity = { dtype = "f64", shape = "(num_velocity_bins, num_height_bins, num_frames, num_locations)" }
radial_velocity = { dtype = "f64", shape = "(num_velocity_bins, num_height_bins, num_frames, num_locations)" }
completeness = { dtype = "b8", shape = "(num_frames,)", default = "one" }

[versions.5-0-0.fields]

[versions.6-0-0]
[versions.6-0-0.attrs]
omega = { dtype = "f64", default = "0.0" }

[versions.6-0-0.datasets]
[versions.6-0-0.fields]
