[general]
name = "VelocityGrid"

[versions.1-0-0]
[versions.1-0-0.attrs]
name = { dtype = "str", default = "UNKNOWN" }
extent = { dtype = "f64", default = "1.0" }
omega = { dtype = "f64", default = "0.0" }

[versions.1-0-0.datasets]
vr_xy = { dtype = "f64", shape = "(num_bins, num_bins, num_frames)" }
vphi_xy = { dtype = "f64", shape = "(num_bins, num_bins, num_frames)" }
completeness = { dtype = "b8", shape = "(num_frames,)", default = "one" }

[versions.1-0-0.fields]
num_frames = { type = "int", value = "num_frames" }
num_bins = { type = "int", value = "num_bins" }


[versions.2-0-0]
[versions.2-0-0.attrs]
[versions.2-0-0.datasets]
vz_xy = { dtype = "f64", shape = "(num_bins, num_bins, num_frames)", default = "zero" }
z_xy = { dtype = "f64", shape = "(num_bins, num_bins, num_frames)", default = "zero" }
[versions.2-0-0.fields]

